esphome:
  name: april-soil
  includes:
      - april_soil_sensor.h
  libraries:
      - Wire

esp32:
  board: esp32-s2-saola-1

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: none

mqtt:
  broker: !secret mqtt_broker

logger:
  level: DEBUG

sensor:
    - platform: adc
      pin: 7
      attenuation: 11db
      name: "VBatt"
      update_interval: 5s

    - platform: custom
      lambda: |-
        auto ab_sensor = new AprilSoilSensor();
        App.register_component(ab_sensor);
        return {ab_sensor->temperature_sensor, ab_sensor->soil_sensor};

      sensors:
      - name: "April temperature"
        unit_of_measurement: °C
        accuracy_decimals: 1
      - name: "April moisture"
        unit_of_measurement: raw

deep_sleep:
  run_duration: 15s
  sleep_duration: 30min
